services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=netbanking-db-1
      - DB_NAME=amren
      - DB_PASSWORD=amren
      - DB_PORT=5432
      - DB_USERNAME=amren
      - DEBUG:"true"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    # environment:
    #   - POSTGRES_USER=amren
    #   - POSTGRES_PASSWORD=netbanking
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/table.sql:/docker-entrypoint-initdb.d/table.sql

volumes:
  db:
    driver: local
