version: '3'
services:
  web:
    env_file:
      - .env
    container_name: netbanking-web-1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=netbanking-db-1
      - DB_NAME=$DB_NAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - DB_USERNAME=$DB_USERNAME
      - DEBUG:"true"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: netbanking-db-1
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/table.sql:/docker-entrypoint-initdb.d/table.sql

volumes:
  db:
    driver: local
